---
version: '3.1'

services:

  db:
    image: mongo:xenial
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: oJuwu7Tohquaongoh9Nooz9vaThaeche
    volumes:
      - './mongodata:/data/db'
    ports:
      - "27017:27017"
    networks:
      - production

  auth:
    image: ku/sund/smartsleep/auth:latest
    build:
      context: ./auth
    environment:
      - NODE_ENV=production
      - CONFIG_ENV=production
    networks:
      - production

  sql:
    image: mysql:5.5
    environment:
      - MYSQL_DATABASES=smartsleep
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_HOST=127.0.0.1
      - MYSQL_PORT=3306
    ports:
      - "33306:3306"
    volumes:
      - "./data:/var/lib/mysql"
    networks:
      - production

  activity:
    image: ku/sund/smartsleep/activity:latest
    build:
      context: ./activity
    networks:
      - production
    secrets:
      - source: activitydb
        target: database.properties

  survey:
    image: limesurvey:latest
    build:
      context: ./limesurvey
    ports:
      - "8081:80"
    networks:
      - production
    secrets:
      - source: limeconfig
        target: config.php

  notify:
    image: ku/sund/smartsleep/notify:latest
    build:
      context: ./notify
    networks:
      - production
    secrets:
      - source: fbadminsdk
        target: firebase-adminsdk.json
      - source: activitydb
        target: database.properties

  proxy:
    image: ku/sund/smartsleep/proxy:latest
    build:
      context: ./proxy
      dockerfile: Dockerfile
    depends_on:
      - auth
      - activity
      - survey
    ports:
      - "18080:8080"
    networks:
      - production

  report-builder:
    image: smartsleep-report-generator
    build:
      context: ./report-builder
    environment:
      - USER_ID=${REPORT_USER}
    volumes:
      - "${BASE_DIR}/ssreports:/reports"
    secrets:
      - db_config

  report-webserver:
    image: smartsleep-report-webserver
    build:
      context: ./report-server
    volumes:
      - "${BASE_DIR}/ssreports:/usr/share/nginx/html/reports:ro"
    ports:
      - 8082:80

  admin-backend:
    image: smartsleep-admin-backend
    build:
      context: ./admin-backend
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - LIMESURVEY_SURVEY_ID=${LIMESURVEY_SURVEY_ID}
      - CSV_DL_URL=${CSV_DL_URL}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - CELERY_BACKEND=${CELERY_BACKEND}
    volumes:
      - "${BASE_DIR}/ssreports:/ssreports"
    ports:
      - 8000:8000
    depends_on:
      - admin-redis
    networks:
      - production
    secrets:
      - db_config
      - admin_config

  admin-celery:
    image: smartsleep-admin-backend
    build:
      context: ./admin-backend
    command: celery -A admin worker -l info
    environment:
      - LIMESURVEY_SURVEY_ID=${LIMESURVEY_SURVEY_ID}
      - CSV_DL_URL=${CSV_DL_URL}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - CELERY_BACKEND=${CELERY_BACKEND}
    volumes:
      - "${BASE_DIR}/ssreports:/ssreports"
    user: ${REPORT_USER}:${REPORT_USER}
    depends_on:
      - admin-redis
    networks:
      - production
    secrets:
      - db_config
      - admin_config

  admin-redis:
    image: smartsleep-admin-redis
    build:
      context: ./admin-redis
    command: redis-server --requirepass ${REDIS_PASS}
    volumes:
      - admin_redis_data:/var/lib/redis
    environment:
      - REDIS_REPLICATION_MODE=master
    networks:
      - production

  admin-frontend:
    image: smartsleep-admin-frontend
    build:
      context: ./admin-frontend
    command: npm start
    stdin_open: true
    ports:
      - 3001:3000
    networks:
      - production

networks:
  production:

volumes:
  admin_redis_data:

secrets:
  activitydb:
    file: ./activity/secrets/database-production.properties
  fbadminsdk:
    file: ./secrets/firebase-adminsdk.json
  limeconfig:
    file: ./secrets/config-production.php
  db_config:
    external: true
  admin_config:
    external: true