"""
Django settings for admin project.

Generated by 'django-admin startproject' using Django 3.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import configparser
import os

import django.core.management.utils

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

db_config = configparser.ConfigParser()
db_config.read('/run/secrets/db_config')
admin_config = configparser.ConfigParser()
admin_config.read('/run/secrets/admin_config')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = django.core.management.utils.get_random_secret_key()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG") == 'True'

ALLOWED_HOSTS = ['*']

CSV_OUT_DIR = '/ssreports'
CSV_DL_URL = os.environ.get("CSV_DL_URL")
LIMESURVEY_BASE = 'http://survey'
LIMESURVEY_PWD = admin_config['admin']['LIMESURVEY_PWD']
LIMESURVEY_USR = admin_config['admin']['LIMESURVEY_USR']
LIMESURVEY_SURVEY_ID = int(os.environ.get("LIMESURVEY_SURVEY_ID"))
MYSQL_HOST = admin_config['admin']['MYSQL_HOST']
MYSQL_PORT = int(admin_config['admin']['MYSQL_PORT'])
MYSQL_USER = admin_config['admin']['MYSQL_USER']
MYSQL_PWD  = admin_config['admin']['MYSQL_PWD']

# CELERY STUFF
BROKER_URL = os.environ.get("CELERY_BACKEND")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_BACKEND")
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Europe/Copenhagen'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'apps.api',
    'apps.users'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'admin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'admin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
        'default': {
            'ENGINE': 'djongo',
            'NAME': 'smartsleep',
            'ENFORCE_SCHEMA': False,
            'CLIENT': {
                'host': db_config['db']['host'],
                'port': int(db_config['db']['port']),
                'username': db_config['db']['username'],
                'password': db_config['db']['password'],
            },
            # 'LOGGING': {
            #     'version': 1,
            #     'loggers': {
            #         'djongo': {
            #             'level': 'DEBUG', #INFO
            #             'propagate': True,
            #         }
            #     },
            #  },
        }
    }



# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
