#!/bin/bash
cd /opt
/opt/conda/bin/jupyter nbconvert --execute --ExecutePreprocessor.timeout=600 --no-input --output-dir /reports/weekly --output `date +report_%y_%m_%d.html` /opt/analysis.ipynb &>> /var/log/cron.log
chown $USER_ID:$USER_ID `date +/reports/weekly/report_%y_%m_%d.html`